#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/common.sh"

usage() {
  cat <<'USAGE'
Usage:
  run_stwm_v4_2_1b_real_confirmation_seed.sh <seed> [out_root]

Description:
  Run one seed of real 1B confirmation with full run matrix:
  - base protocol: full_v4_2, wo_semantics_v4_2, wo_object_bias_v4_2
  - state-identifiability protocol: full_v4_2, wo_semantics_v4_2, wo_object_bias_v4_2
  - harder-protocol decoupling generated by protocol scripts

Environment knobs (defaults are real-budget profile):
  STWM_V4_2_REAL_1B_RUNS=full_v4_2,wo_semantics_v4_2,wo_object_bias_v4_2
  STWM_V4_2_REAL_1B_BASE_STEPS=900
  STWM_V4_2_REAL_1B_STATE_STEPS=240
  STWM_V4_2_REAL_1B_BASE_SAMPLE_LIMIT=<clip_count_of_base_manifest>
  STWM_V4_2_REAL_1B_STATE_SAMPLE_LIMIT=18
USAGE
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

SEED="$1"
OUT_ROOT="${2:-$STWM_ROOT/outputs/training/stwm_v4_2_1b_real_confirmation}"

if ! [[ "$SEED" =~ ^[0-9]+$ ]]; then
  echo "seed must be an integer, got: $SEED" >&2
  exit 1
fi

RUNS_CSV="${STWM_V4_2_REAL_1B_RUNS:-full_v4_2,wo_semantics_v4_2,wo_object_bias_v4_2}"
BASE_STEPS="${STWM_V4_2_REAL_1B_BASE_STEPS:-900}"
STATE_STEPS="${STWM_V4_2_REAL_1B_STATE_STEPS:-240}"

BASE_MANIFEST="${STWM_V4_2_MANIFEST:-$STWM_ROOT/manifests/minisplits/stwm_week2_minival_v2.json}"
BASE_CLIP_COUNT="$(grep -o '"clip_id"' "$BASE_MANIFEST" | wc -l | tr -d ' ')"
if ! [[ "$BASE_CLIP_COUNT" =~ ^[0-9]+$ ]] || (( BASE_CLIP_COUNT <= 0 )); then
  BASE_CLIP_COUNT=70
fi

BASE_SAMPLE_LIMIT="${STWM_V4_2_REAL_1B_BASE_SAMPLE_LIMIT:-$BASE_CLIP_COUNT}"
STATE_SAMPLE_LIMIT="${STWM_V4_2_REAL_1B_STATE_SAMPLE_LIMIT:-18}"

BASE_ROOT="$OUT_ROOT/base"
STATE_ROOT="$OUT_ROOT/state"
STATUS_DIR="$OUT_ROOT/status"
STATUS_FILE="$STATUS_DIR/seed_${SEED}.status"

mkdir -p "$OUT_ROOT" "$STATUS_DIR"

start_ts="$(timestamp)"
echo "[1b-real] start seed=${SEED} start_ts=${start_ts}"
echo "[1b-real] runs=${RUNS_CSV} base_steps=${BASE_STEPS} state_steps=${STATE_STEPS}"
echo "[1b-real] base_manifest=${BASE_MANIFEST} base_sample_limit=${BASE_SAMPLE_LIMIT} state_sample_limit=${STATE_SAMPLE_LIMIT}"

echo "[1b-real] step=base_protocol"
STWM_V4_2_1B_MINIVAL_SEEDS="$SEED" \
STWM_V4_2_1B_MINIVAL_RUNS="$RUNS_CSV" \
STWM_V4_2_1B_MINIVAL_STEPS="$BASE_STEPS" \
STWM_V4_2_1B_MINIVAL_SAMPLE_LIMIT="$BASE_SAMPLE_LIMIT" \
STWM_V4_2_1B_MINIVAL_SKIP_EXISTING=0 \
  bash "$SCRIPT_DIR/run_stwm_v4_2_1b_minival_multiseed.sh" "$BASE_ROOT"

echo "[1b-real] step=state_identifiability_protocol"
STWM_V4_2_1B_IDENTIFIABILITY_SEEDS="$SEED" \
STWM_V4_2_1B_IDENTIFIABILITY_RUNS="$RUNS_CSV" \
STWM_V4_2_1B_IDENTIFIABILITY_EVAL_STEPS="$STATE_STEPS" \
STWM_V4_2_1B_IDENTIFIABILITY_SAMPLE_LIMIT="$STATE_SAMPLE_LIMIT" \
STWM_V4_2_1B_IDENTIFIABILITY_SKIP_EXISTING=0 \
STWM_V4_2_1B_IDENTIFIABILITY_BUILD_FIGURES=0 \
STWM_V4_2_1B_IDENTIFIABILITY_SAVE_CHECKPOINT=1 \
STWM_V4_2_1B_IDENTIFIABILITY_CHECKPOINT_NAME=eval_model.pt \
STWM_V4_2_1B_BASE_RUNS_ROOT="$BASE_ROOT" \
  bash "$SCRIPT_DIR/run_stwm_v4_2_1b_state_identifiability.sh" "$STATE_ROOT"

end_ts="$(timestamp)"

cat > "$STATUS_FILE" <<EOF
seed=${SEED}
start_ts=${start_ts}
end_ts=${end_ts}
runs=${RUNS_CSV}
base_steps=${BASE_STEPS}
state_steps=${STATE_STEPS}
base_manifest=${BASE_MANIFEST}
base_sample_limit=${BASE_SAMPLE_LIMIT}
state_sample_limit=${STATE_SAMPLE_LIMIT}
base_root=${BASE_ROOT}
state_root=${STATE_ROOT}
base_summary=${BASE_ROOT}/comparison_multiseed.json
state_summary=${STATE_ROOT}/comparison_state_identifiability.json
base_decoupling=${STWM_ROOT}/reports/stwm_v4_2_1b_query_decoupling_multiseed.json
state_decoupling=${STWM_ROOT}/reports/stwm_v4_2_1b_state_identifiability_decoupling_v1.json
EOF

echo "[1b-real] seed done: ${SEED}"
echo "  status_file:  $STATUS_FILE"
echo "  base_root:    $BASE_ROOT"
echo "  state_root:   $STATE_ROOT"
